[package]
name = "drive-transfer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
drive-api-client = { path = "../drive-api-client", version = "0.5.0" }
drive-local-index = { path = "../drive-local-index", version = "0.5.0" }
drive-platform = { path = "../drive-platform", version = "0.5.0" }
futures-util.workspace = true
hex.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
