from __future__ import annotations

SHARE_TYPE_INTERNAL = "internal"
SHARE_TYPE_EXTERNAL = "external"
SHARE_TYPES = frozenset({SHARE_TYPE_INTERNAL, SHARE_TYPE_EXTERNAL})

SHARE_STATUS_ACTIVE = "active"
SHARE_STATUS_EXPIRED = "expired"
SHARE_STATUS_REVOKED = "revoked"
SHARE_STATUS_DISABLED = "disabled"
SHARE_STATUSES = frozenset(
    {
        SHARE_STATUS_ACTIVE,
        SHARE_STATUS_EXPIRED,
        SHARE_STATUS_REVOKED,
        SHARE_STATUS_DISABLED,
    }
)

SHARE_PERMISSION_PREVIEW = "preview"
SHARE_PERMISSION_DOWNLOAD = "download"
SHARE_PERMISSIONS = frozenset({SHARE_PERMISSION_PREVIEW, SHARE_PERMISSION_DOWNLOAD})

SHARE_RECIPIENT_USER = "user"
SHARE_RECIPIENT_DEPARTMENT = "department"
SHARE_RECIPIENT_GROUP = "group"
SHARE_RECIPIENT_TYPES = frozenset(
    {SHARE_RECIPIENT_USER, SHARE_RECIPIENT_DEPARTMENT, SHARE_RECIPIENT_GROUP}
)
