from __future__ import annotations

SPACE_ROLE_OWNER = "owner"
SPACE_ROLE_ADMIN = "admin"
SPACE_ROLE_EDITOR = "editor"
SPACE_ROLE_VIEWER = "viewer"

SPACE_ROLES = frozenset(
    {
        SPACE_ROLE_OWNER,
        SPACE_ROLE_ADMIN,
        SPACE_ROLE_EDITOR,
        SPACE_ROLE_VIEWER,
    }
)

ACL_SUBJECT_USER = "user"
ACL_SUBJECT_DEPARTMENT = "department"
ACL_SUBJECT_GROUP = "group"
ACL_SUBJECT_TYPES = frozenset({ACL_SUBJECT_USER, ACL_SUBJECT_DEPARTMENT, ACL_SUBJECT_GROUP})

ACL_EFFECT_ALLOW = "allow"
ACL_EFFECT_DENY = "deny"
ACL_EFFECTS = frozenset({ACL_EFFECT_ALLOW, ACL_EFFECT_DENY})
